### ISSUE TITLE
Error when downloading taskset

### ISSUE THREAD

**Issue by theodorju** [automl/ifBO#1]
Hi all, I've built a conda environment with the README commands and installed `core_requirements.txt`. Then when trying to download `taskset` with `python -m mfpbench download --benchmark taskset-tabular` the following error is raised: `TypeError: object cannot be converted to an IntegerDtype`.

This seems to be related with pandas. After installing pandas version 2.2.2 (v. 1.3.5 is suggested in core requirements) and tensorflow (2.16.1) (which seems to be required for taskset) the benchmark downloads successfully.

**Comment by herilalaina** [comment]
Thanks a lot! It has been fixed now.
