### ISSUE TITLE
[Docs] What are acceptable ranges for a) hyperparameters b) performance values?

### ISSUE THREAD

**Issue by eddiebergman** [automl/ifBO#14]
The only thing I could conclude from he example is that you are maximizing performance. It also seems that he example prefers everything `0-1` normalized, is this required/preffered, are there issues with not doing this?

**Comment by herilalaina** [comment]
Both the hyperparameters and performance values should be in $[0-1]$. Any values outside of this range will trigger an exception ([see](https://github.com/automl/ifBO/blob/cbbde2576ee300216ee39c302bfbc882f845e757/ifbo/surrogate.py#L122)).
