### ISSUE TITLE
Possible bug in cumulative fidelity calculation for ifbo

### ISSUE THREAD

**Issue by theodorju** [automl/ifBO#17]
After re-running some of the experiments and trying to replicate the normalized regret plots I noticed that the cumulative fidelity for ifbo might be calculated incorrectly.

I'm not exactly sure where the root cause of this issue lies, but the way cumulative fidelity is calculated based on this line
https://github.com/automl/ifBO/blob/9e7aee86424941eb862e02e854b170d16aa9e7f3/src/pfns_hpo/pfns_hpo/regret_plot.py#L171

does not correctly take into account that in ifbo runs are essentially continued and not started from scratch.

Here is an extract from the neps logs of one ifbo optimization run
<!DOCTYPE html>

<html>
<head>

</head>

<body>

Config_id | config.epoch | result.info_dict.fidelity | cumsum_fidelity
-- | -- | -- | --
0_0 | 1 | 1 | 1
1_0 | 1 | 1 | 2
2_0 | 1 | 1 | 3
2_1 | 2 | 2 | 5 <-- jump (+2)
3_0 | 1 | 1 | 6
4_0 | 1 | 1 | 7
5_0 | 1 | 1 | 8
6_0 | 1 | 1 | 9
7_0 | 1 | 1 | 10
8_0 | 1 | 1 | 11
9_0 | 1 | 1 | 12
8_1 | 2 | 2 | 14 <-- jump (+2)
8_2 | 3 | 3 | 17 <-- jump (+3)
2_2 | 3 | 3 | 20 <-- jump (+3)
2_3 | 4 | 4 | 24 <-- jump (+4)

</body>

</html>

The jumps in cumulative fidelity suggest the runs for specific configurations are not continued but instead start from zero.
I would assume that the correct calculation would be:

<!DOCTYPE html>

<html>
<head>

</head>

<body>

Config_id | config.epoch | result.info_dict.fidelity | cumsum_fidelity
-- | -- | -- | --
0_0 | 1 | 1 | 1
1_0 | 1 | 1 | 2
2_0 | 1 | 1 | 3
2_1 | 2 | 2 | 4
3_0 | 1 | 1 | 5
4_0 | 1 | 1 | 6
5_0 | 1 | 1 | 7
6_0 | 1 | 1 | 8
7_0 | 1 | 1 | 9
8_0 | 1 | 1 | 10
9_0 | 1 | 1 | 11
8_1 | 2 | 2 | 12 
8_2 | 3 | 3 | 13 
2_2 | 3 | 3 | 14
2_3 | 4 | 4 | 15

</body>
</html>

**Comment by Neeratyoy** [comment]
That is certainly a correct observation in terms of what is expected.

However, the [line above](https://github.com/automl/ifBO/blob/9e7aee86424941eb862e02e854b170d16aa9e7f3/src/pfns_hpo/pfns_hpo/regret_plot.py#L168) what you shared, and this part [here](https://github.com/automl/ifBO/blob/9e7aee86424941eb862e02e854b170d16aa9e7f3/src/pfns_hpo/pfns_hpo/regret_plot.py#L109C9-L109C16) should be handling precisely what you are saying.

Is it then that the `--continuations` flag in the script is not working as expected?

**Comment by theodorju** [comment]
Thanks for the reply @Neeratyoy. I executed that experiment with the `just submit` command and I'm not sure if the `--continuations` flag was present there. I'll have a look into it and will either update or close this issue.

**Comment by theodorju** [comment]
Sorry @Neeratyoy the mistake was on my side with the `--continuations` flag. I'll go ahead and close this one.
