### ISSUE TITLE
HPO png plots after neps runs are generated with missing info

### ISSUE THREAD

**Issue by theodorju** [automl/ifBO#8]
Due to this line in the code:
https://github.com/automl/ifBO/blob/6f2b6129d6b72e21a99e8e5a775c920d6bd310cf/src/pfns_hpo/pfns_hpo/run.py#L340

the png showing the learning curves after HPO runs is generated with missing information. 

Specifically, the name of the png is `Plot3d_None_None_None_None.png` and it's title is `alg: None, benchmark: None, seed:None`.

I think this can be fixed if the line above is replaced with:
```
  plotter = Plotter3D(
      algorithm=args.algorithm.name,
      benchmark=args.benchmark.name,
      experiment_group=args.experiment_group,
      seed=args.seed
  )
```

then the name of the generated PNG and the plot title will correctly include the experiment group, benchmark, seed, and algorithm information.

Should I go ahead and commit this change?

**Comment by herilalaina** [comment]
thanks @theodorju ! Could you create a PR for the ``icml-2024`` branch? We will merge from there.

**Comment by theodorju** [comment]
Closing this as completed.
